/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EscrowLibrary {
  export type EscrowDataStruct = {
    client: AddressLike;
    freelancer: AddressLike;
    arbitrator: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    currentState: BigNumberish;
    createdAt: BigNumberish;
    milestoneCompleted: boolean;
  };

  export type EscrowDataStructOutput = [
    client: string,
    freelancer: string,
    arbitrator: string,
    amount: bigint,
    deadline: bigint,
    currentState: bigint,
    createdAt: bigint,
    milestoneCompleted: boolean
  ] & {
    client: string;
    freelancer: string;
    arbitrator: string;
    amount: bigint;
    deadline: bigint;
    currentState: bigint;
    createdAt: bigint;
    milestoneCompleted: boolean;
  };
}

export interface IEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveAndRelease"
      | "completeMilestone"
      | "createEscrow"
      | "getEscrowCounter"
      | "getEscrowDetails"
      | "getState"
      | "raiseDispute"
      | "refund"
      | "resolveDispute"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveAndRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveAndRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
}

export interface IEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IEscrow;
  waitForDeployment(): Promise<this>;

  interface: IEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveAndRelease: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeMilestone: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [freelancer: AddressLike, arbitrator: AddressLike, deadline: BigNumberish],
    [bigint],
    "payable"
  >;

  getEscrowCounter: TypedContractMethod<[], [bigint], "view">;

  getEscrowDetails: TypedContractMethod<
    [escrowId: BigNumberish],
    [EscrowLibrary.EscrowDataStructOutput],
    "view"
  >;

  getState: TypedContractMethod<[escrowId: BigNumberish], [bigint], "view">;

  raiseDispute: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  refund: TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [escrowId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveAndRelease"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeMilestone"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [freelancer: AddressLike, arbitrator: AddressLike, deadline: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getEscrowCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrowDetails"
  ): TypedContractMethod<
    [escrowId: BigNumberish],
    [EscrowLibrary.EscrowDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getState"
  ): TypedContractMethod<[escrowId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [escrowId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
